CREATE TABLE IF NOT EXISTS "AuthUsers" (
    "Id" SERIAL PRIMARY KEY,
    "Username" VARCHAR(64) NOT NULL UNIQUE,
    "Email" VARCHAR(255) NOT NULL UNIQUE,
    "PasswordHash" TEXT NOT NULL,
    "Role" VARCHAR(32) NOT NULL DEFAULT 'User',
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "RefreshTokens" (
    "Id" SERIAL PRIMARY KEY,
    "Token" TEXT NOT NULL UNIQUE,
    "Expires" TIMESTAMP NOT NULL,
    "IsRevoked" BOOLEAN NOT NULL DEFAULT FALSE,
    "UserId" INT NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY ("UserId") REFERENCES "AuthUsers"("Id") ON DELETE CASCADE
);
