CREATE TABLE IF NOT EXISTS "AuthUsers" (
    "Id" SERIAL PRIMARY KEY,
    "Username" VARCHAR(64) NOT NULL UNIQUE,
    "Email" VARCHAR(255) NOT NULL UNIQUE,
    "PasswordHash" TEXT NOT NULL,
    "Role" VARCHAR(32) NOT NULL DEFAULT 'User',
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
