services:
  mysql:
    image: mysql:8.0
    container_name: MySQL_Database
    environment:
      MYSQL_DATABASE: RESTful
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d # For initializing schema with mock data
      - ./mysql/mysql_data:/var/lib/mysql

volumes:
  mysql_data:
