name: CI/CD Pipeline # Workflow name

on:
  # Trigger on pull and push
  push:
    branches: [ main ]
  
  pull_request:
    branches: [ main ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

        # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

        # Cache NuGet packages
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

        # Restoring dependencies
      - name: Restore dependencies
        run: dotnet restore

        # Code quality checks
      - name: Format check
        run: dotnet format --verify-no-changes --verbosity diagnostic

        # Build project
      - name: Build
        run: dotnet build --no-restore --configuration Release

        # Run tests
      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Test with Coverage
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory ./coverage

        # Upload coverage report
      - name: Upload coverage to reports
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage

        # Publish project (if project deployed, otherwise skip this step)
      - name: Publish
        run: dotnet publish --no-build --configuration Release --output ./publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RESTfulAPI
          path: ./publish